image:
  registry: "897074277336.dkr.ecr.us-east-1.amazonaws.com" # set once during setup — terraform output ecr_repository_urls, minus the repo name
backend:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: 750m
      memory: 768Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 65
  env:
    NODE_ENV: production
    LOG_LEVEL: info
    RATE_LIMIT_MAX: "200"
    DB_POOL_MAX: "20"
    DB_POOL_MIN: "5"
    JWT_EXPIRES_IN: "8h"
    JWT_REFRESH_EXPIRES_IN: "7d"
  image:
    tag: prod-24b8c57-59
frontend:
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    tag: prod-24b8c57-59
ingress:
  hosts:
    frontend: app.rashmidevops.xyz
    backend: api.rashmidevops.xyz
  tls:
    certificateArn: "arn:aws:acm:us-east-1:897074277336:certificate/6d81c644-658f-4f44-98d7-8b3f3b7d6475" # set once during setup — terraform output acm_certificate_arn